name: API Stability CI

on:
  workflow_dispatch:

jobs:
  build_linux:
    name: Check Swift API Stability on Linux.
    runs-on: ubuntu-latest

    steps:
      - name: Install Swift
        uses: slashmo/install-swift@v0.4.0
        with:
          version: "5.10"
      
      - name: Setup SSH Key
        run: | 
          rm -rf ~/.ssh
          mkdir -m 0700 ~/.ssh
          echo "${{ secrets.WORKFLOWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.WORKFLOWS_SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
          chmod 0600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
      
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Check API Stability 
        run: swift package diagnose-api-breaking-changes `git describe --tags --abbrev=0`
  
  build_macos:
    name: Check Swift API Stability on MacOs.
    runs-on: macos-latest
    steps:
      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Setup SSH Key
        run: | 
          rm -rf ~/.ssh
          mkdir -m 0700 ~/.ssh
          echo "${{ secrets.WORKFLOWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.WORKFLOWS_SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
          chmod 0600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      
      #- name: Reconfigure Private Repo URLs
      #  run: sed -i 's/git@github.com:/https:\/\/${{ secrets.ACCESS_TOKEN }}@github.com\//g' Package.swift

      - name: Check API Stability 
        run: swift package diagnose-api-breaking-changes `git describe --tags --abbrev=0`
  
  build_windows:
    name: Check Swift API Stability on Windows.
    runs-on: windows-latest
    steps:
      - name: Setup Swift
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.9.2-release
          tag: 5.9.2-RELEASE
      
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.WORKFLOWS_SSH_PRIVATE_KEY }}

      - name: Disable NTFS protection
        run: git config --global core.protectNTFS false
      
      - name: Clone dependencies
        run: swift package update

      - name: Check API Stability
        shell: bash
        run: swift package diagnose-api-breaking-changes `git describe --tags --abbrev=0`
      
